# Generated by Django 3.2.6 on 2022-11-23 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_data', models.DateField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('runnig_time', models.CharField(max_length=150)),
                ('video', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_data', models.DateField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('runnig_time', models.CharField(max_length=150)),
                ('video', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
